# Generated by Django 4.1.4 on 2022-12-17 13:10

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('desc', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(upload_to=main_page.models.Events.get_file)),
                ('date', models.DateTimeField(unique=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='WhyOur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_about', models.BooleanField(default=False)),
                ('desc', models.TextField(max_length=500)),
                ('video', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ('position',)},
        ),
    ]
