# Generated by Django 4.1.4 on 2022-12-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_events_desc_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='paragraph_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='paragraph_2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='paragraph_3',
            field=models.TextField(default='', max_length=100),
        ),
    ]
