# Generated by Django 4.1.4 on 2022-12-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_events_paragraph_1_events_paragraph_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_bold', models.CharField(blank=True, max_length=50)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('desc_1', models.TextField(max_length=200)),
                ('desc_2', models.TextField(max_length=200)),
                ('paragraph_1', models.TextField(max_length=100)),
                ('paragraph_2', models.TextField(max_length=100)),
                ('paragraph_3', models.TextField(max_length=100)),
                ('desc_final', models.TextField(max_length=200)),
                ('video', models.URLField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
