# Generated by Django 4.1.4 on 2022-12-22 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_userreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='times',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='введіть час в форматі хх:хх', regex='^\\d{2}.\\d{2}')]),
        ),
    ]
