# Generated by Django 4.1.4 on 2022-12-22 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_rename_email_userreservation_email_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='times',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='введіть час в форматі хх:хх', regex='^\\d{2}.\\d{2}')]),
        ),
    ]
